### ISSUE TITLE
Failed build related to OpenSSL

### ISSUE THREAD

**Issue by JohnOmernik** [zeek/zeek-docker#2]
CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:293 (list):
  list GET given empty list
Call Stack (most recent call first):
  aux/broccoli/cmake/FindRequiredPackage.cmake:26 (find_package)
  aux/broccoli/CMakeLists.txt:48 (FindRequiredPackage)

CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:294 (list):
  list GET given empty list
Call Stack (most recent call first):
  aux/broccoli/cmake/FindRequiredPackage.cmake:26 (find_package)
  aux/broccoli/CMakeLists.txt:48 (FindRequiredPackage)

CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:296 (list):
  list GET given empty list
Call Stack (most recent call first):
  aux/broccoli/cmake/FindRequiredPackage.cmake:26 (find_package)
  aux/broccoli/CMakeLists.txt:48 (FindRequiredPackage)

CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:298 (list):
  list GET given empty list
Call Stack (most recent call first):
  aux/broccoli/cmake/FindRequiredPackage.cmake:26 (find_package)
  aux/broccoli/CMakeLists.txt:48 (FindRequiredPackage)
- Configuring incomplete, errors occurred!
  See also "/scratch/bro/build/CMakeFiles/CMakeOutput.log".
  See also "/scratch/bro/build/CMakeFiles/CMakeError.log".
  The command '/bin/sh -c ${WD}/common/gitbro 49ca47895db45e03b9ab918292af6d525c42f94e' returned a non-zero code: 1

**Comment by JustinAzoff** [comment]
I'm rebuilding the master container today.. I ran into an issue with swig on debian jessie and switched to stretch to work around that. (I believe swig will be replaced by pybind soon anyway)...

I didn't run into any openssl issues though, everything built ok the first time.

I'm not sure what the issue was, but the container should build cleanly from the current master.Dockerfile as of b2a0dc97e52efea26bd97a2b8d0caa336a0c4e03
